// Copyright 2023 karliss (@karliss)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define RGB_MATRIX_LED_COUNT 68
#define SN32_RGB_MATRIX_ROW_PINS \
    { C4, C6, C5, C7, C9, C8, C10, C12, C11, B6, B8, B7, B9, B11, B10 }

#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define RGB_MATRIX_KEYPRESSES
#define RGB_MATRIX_TYPING_HEATMAP_DECREASE_DELAY_MS 50

#define MATRIX_UNSELECT_DRIVE_HIGH
#define SN32_RGB_OUTPUT_ACTIVE_LEVEL SN32_RGB_OUTPUT_ACTIVE_LOW
#define SN32_PWM_OUTPUT_ACTIVE_LEVEL SN32_PWM_OUTPUT_ACTIVE_HIGH

#define TRANSIENT_EEPROM_SIZE 1024
